[package]
name = "certbot-alfahosting"
version = "0.1.0"
authors = ["Lukas Wagner <appdev.lukaswagner@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
headless_chrome = "0.9.0"
acme-lib = "0.5.2"